# 1. 데이터 로드

In [1]:
import pandas as pd
selloutData = pd.read_csv("../Python_ST_EX/dataset/kopo_channel_seasonality_new.csv")
selloutData.head(1)

  REGIONID   PRODUCT  YEARWEEK   QTY
0      A60  PRODUCT4    201402  71.0

# 2. 데이터 정제하기

## 데이터가 음수인 값 양수로 변경

In [11]:
import numpy as np
selloutData["NEW_QTY"] = np.where(selloutData["QTY"] < 0, 0, selloutData["QTY"])
selloutData[selloutData.QTY < 0].head(1)

   REGIONID    PRODUCT  YEARWEEK  QTY  NEW_QTY
65      A02  PRODUCT16    201403 -1.0      0.0

## 53주차 제거

In [10]:
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK      int64
QTY         float64
NEW_QTY     float64
dtype: object

In [72]:
# YEARWEEK가 Int형일 경우 처리
refinedData = selloutData[selloutData.YEARWEEK % 100 < 53]
refinedData[refinedData.YEARWEEK % 100 > 52]

Empty DataFrame
Columns: [REGIONID, PRODUCT, YEARWEEK, QTY, NEW_QTY]
Index: []

## 연주차 정보 분리

In [78]:
# "//" 연산자는 결과를 정수형으로 산출 "/" 연산자는 실수형으로 산출
refinedData["YEAR"] = refinedData["YEARWEEK"] // 100
refinedData["WEEK"] = refinedData["YEARWEEK"] % 100
refinedData = refinedData[["REGIONID", "PRODUCT", "YEARWEEK", "YEAR", "WEEK", "QTY", "NEW_QTY"]]
refinedData.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

  REGIONID    PRODUCT  YEARWEEK  YEAR  WEEK      QTY  NEW_QTY
0      A60   PRODUCT4    201402  2014     2     71.0     71.0
1      A60  PRODUCT59    201402  2014     2  22275.0  22275.0
2      A60  PRODUCT34    201402  2014     2   4463.0   4463.0
3      A60  PRODUCT47    201402  2014     2      0.0      0.0
4      A60  PRODUCT56    201402  2014     2     23.0     23.0

In [111]:
sortKey = ["REGIONID", "PRODUCT", "YEARWEEK"]
# drop이 True면 기존의 인덱스를 없앤다는 뜻
sortedData = refinedData.sort_values(sortKey).reset_index(drop=True)
sortedData.head(20)

   REGIONID    PRODUCT  YEARWEEK  YEAR  WEEK    QTY  NEW_QTY
0       A00  PRODUCT34    201401  2014     1  661.0    661.0
1       A00  PRODUCT34    201402  2014     2  679.0    679.0
2       A00  PRODUCT34    201403  2014     3  578.0    578.0
3       A00  PRODUCT34    201404  2014     4  532.0    532.0
4       A00  PRODUCT34    201405  2014     5  516.0    516.0
5       A00  PRODUCT34    201406  2014     6  423.0    423.0
6       A00  PRODUCT34    201407  2014     7  407.0    407.0
7       A00  PRODUCT34    201408  2014     8  364.0    364.0
8       A00  PRODUCT34    201409  2014     9  470.0    470.0
9       A00  PRODUCT34    201410  2014    10  538.0    538.0
10      A00  PRODUCT34    201411  2014    11  369.0    369.0
11      A00  PRODUCT34    201412  2014    12  352.0    352.0
12      A00  PRODUCT34    201413  2014    13  354.0    354.0
13      A00  PRODUCT34    201414  2014    14  312.0    312.0
14      A00  PRODUCT34    201415  2014    15  295.0    295.0
15      A00  PRODUCT34    201416  2014    16  284.0    284.0
16      A00  PRODUCT34    201417  2014    17  237.0    237.0
17      A00  PRODUCT34    201418  2014    18  180.0    180.0
18      A00  PRODUCT34    201419  2014    19  161.0    161.0
19      A00  PRODUCT34    201420  2014    20  140.0    140.0

# 3. 이동평균 구하기

In [110]:
step1Data = sortedData
order = 5
suborder = order // 2
suborder

2

In [125]:
step1Data["MA"] = step1Data.NEW_QTY.rolling(window = 15, center = True, min_periods = 8).mean()
step1Data["MSTD"] = step1Data.MA.rolling(window = 9, center = True, min_periods = 5).std(ddof = 1)
step1Data.head()

,REGIONID,PRODUCT,YEARWEEK,YEAR,WEEK,QTY,NEW_QTY,MA,MSTD
0,A00,PRODUCT34,201401,2014,1,661.0,661.0,520.000000,12.002994
1,A00,PRODUCT34,201402,2014,2,679.0,679.0,514.444444,15.933923
2,A00,PRODUCT34,201403,2014,3,578.0,578.0,516.800000,19.930825
3,A00,PRODUCT34,201404,2014,4,532.0,532.0,503.363636,23.784855
4,A00,PRODUCT34,201405,2014,5,516.0,516.0,490.750000,30.428905

# 4. 그룹화

In [308]:
groupKey = ["REGIONID","PRODUCT","YEAR"]
groupData = step1Data.groupby(groupKey, as_index = False)[["NEW_QTY"]].mean()
groupData.columns = ["REGIONID", "PRODUCT","YEAR","GROUP"]
groupData.head()

  REGIONID    PRODUCT  YEAR       GROUP
0      A00  PRODUCT34  2014  275.961538
1      A00  PRODUCT34  2015   86.634615
2      A00  PRODUCT34  2016   36.576923
3      A00  PRODUCT58  2014    2.673077
4      A00  PRODUCT58  2015    5.711538

# 5. 데이터 합치기

In [309]:
mergedData = pd.merge(step1Data, groupData, on = groupKey, how = "left")
mergedData.tail()

,REGIONID,PRODUCT,YEARWEEK,YEAR,WEEK,QTY,NEW_QTY,MA,MSTD,GROUP
123859,A77,PRODUCT12,201648,2016,48,4152.0,4152.0,4839.500000,260.550638,4837.153846
123860,A77,PRODUCT12,201649,2016,49,5086.0,5086.0,4914.909091,274.767625,4837.153846
123861,A77,PRODUCT12,201650,2016,50,5846.0,5846.0,4977.200000,229.386294,4837.153846
123862,A77,PRODUCT12,201651,2016,51,4933.0,4933.0,4890.222222,91.131622,4837.153846
123863,A77,PRODUCT12,201652,2016,52,7551.0,7551.0,4987.875000,61.751302,4837.153846

# 6. 그룹화 함수 만들기

In [310]:
groupKey = ["REGIONID","PRODUCT"]
groupDataSet = mergedData.groupby(groupKey)
groupDataSet

In [311]:
len(list(groupDataSet.groups))

794

In [321]:
oneGroup = groupDataSet.get_group(list(groupDataSet.groups)[0])
oneGroup

,REGIONID,PRODUCT,YEARWEEK,YEAR,WEEK,QTY,NEW_QTY,MA,MSTD,GROUP,MA3
0,A00,PRODUCT34,201401,2014,1,661.0,661.0,520.000000,12.002994,275.961538,520.000000
1,A00,PRODUCT34,201402,2014,2,679.0,679.0,514.444444,15.933923,275.961538,514.444444
2,A00,PRODUCT34,201403,2014,3,578.0,578.0,516.800000,19.930825,275.961538,516.800000
3,A00,PRODUCT34,201404,2014,4,532.0,532.0,503.363636,23.784855,275.961538,503.363636
4,A00,PRODUCT34,201405,2014,5,516.0,516.0,490.750000,30.428905,275.961538,490.750000
5,A00,PRODUCT34,201406,2014,6,423.0,423.0,480.230769,38.666084,275.961538,480.230769
6,A00,PRODUCT34,201407,2014,7,407.0,407.0,468.214286,47.192218,275.961538,468.214286
7,A00,PRODUCT34,201408,2014,8,364.0,364.0,456.666667,53.509329,275.961538,456.666667
8,A00,PRODUCT34,201409,2014,9,470.0,470.0,431.533333,59.591171,275.961538,431.533333
9,A00,PRODUCT34,201410,2014,10,538.0,538.0,402.066667,64.038426,275.961538,402.066667
10,A00,PRODUCT34,201411,2014,11,369.0,369.0,375.533333,66.380349,275.961538,375.533333
11,A00,PRODUCT34,201412,2014,12,352.0,352.0,350.800000,66.197096,275.961538,350.800000
12,A00,PRODUCT34,201413,2014,13,354.0,354.0,325.733333,64.231478,275.961538,325.733333
13,A00,PRODUCT34,201414,2014,14,312.0,312.0,305.266667,63.843278,275.961538,305.266667
14,A00,PRODUCT34,201415,2014,15,295.0,295.0,284.666667,63.749723,275.961538,284.666667
15,A00,PRODUCT34,201416,2014,16,284.0,284.0,265.933333,63.198917,275.961538,265.933333
16,A00,PRODUCT34,201417,2014,17,237.0,237.0,239.333333,61.427301,275.961538,239.333333
17,A00,PRODUCT34,201418,2014,18,180.0,180.0,207.800000,57.375527,275.961538,207.800000
18,A00,PRODUCT34,201419,2014,19,161.0,161.0,187.200000,49.053944,275.961538,187.200000
19,A00,PRODUCT34,201420,2014,20,140.0,140.0,169.200000,38.741811,275.961538,169.200000
20,A00,PRODUCT34,201421,2014,21,116.0,116.0,155.666667,27.242451,275.961538,155.666667
21,A00,PRODUCT34,201422,2014,22,98.0,98.0,153.133333,19.953467,275.961538,153.133333
22,A00,PRODUCT34,201423,2014,23,83.0,83.0,168.933333,21.837712,275.961538,168.933333
23,A00,PRODUCT34,201424,2014,24,71.0,71.0,179.933333,27.119202,275.961538,179.933333
24,A00,PRODUCT34,201425,2014,25,65.0,65.0,193.000000,31.179979,275.961538,193.000000
25,A00,PRODUCT34,201426,2014,26,60.0,60.0,205.266667,32.091497,275.961538,205.266667
26,A00,PRODUCT34,201427,2014,27,82.0,82.0,217.600000,29.774486,275.961538,217.600000
27,A00,PRODUCT34,201428,2014,28,151.0,151.0,229.066667,27.962398,275.961538,229.066667
28,A00,PRODUCT34,201429,2014,29,274.0,274.0,237.600000,25.816728,275.961538,237.600000
29,A00,PRODUCT34,201430,2014,30,532.0,532.0,246.200000,23.610884,275.961538,246.200000
...,...,...,...,...,...,...,...,...,...,...,...
126,A00,PRODUCT34,201623,2016,23,7.0,7.0,34.600000,15.010914,36.576923,34.600000
127,A00,PRODUCT34,201624,2016,24,7.0,7.0,34.533333,13.436825,36.576923,34.533333
128,A00,PRODUCT34,201625,2016,25,5.0,5.0,39.733333,10.258137,36.576923,39.733333
129,A00,PRODUCT34,201626,2016,26,7.0,7.0,39.200000,2.321425,36.576923,39.200000
130,A00,PRODUCT34,201627,2016,27,3.0,3.0,39.333333,3.109384,36.576923,39.333333
131,A00,PRODUCT34,201628,2016,28,19.0,19.0,39.066667,14.494243,36.576923,39.066667
132,A00,PRODUCT34,201629,2016,29,419.0,419.0,38.800000,18.822262,36.576923,38.800000
133,A00,PRODUCT34,201630,2016,30,6.0,6.0,38.866667,22.156759,36.576923,38.866667
134,A00,PRODUCT34,201631,2016,31,7.0,7.0,45.133333,23.767906,36.576923,45.133333
135,A00,PRODUCT34,201632,2016,32,82.0,82.0,82.066667,23.896583,36.576923,82.066667
136,A00,PRODUCT34,201633,2016,33,2.0,2.0,82.866667,21.924782,36.576923,82.866667
137,A00,PRODUCT34,201634,2016,34,8.0,8.0,87.400000,19.331718,36.576923,87.400000
138,A00,PRODUCT34,201635,2016,35,4.0,4.0,87.866667,15.875480,36.576923,87.866667
139,A00,PRODUCT34,201636,2016,36,2.0,2.0,87.333333,13.646326,36.576923,87.333333
140,A00,PRODUCT34,201637,2016,37,5.0,5.0,60.400000,14.275612,36.576923,60.400000
141,A00,PRODUCT34,201638,2016,38,101.0,101.0,61.200000,14.153563,36.576923,61.200000
142,A00,PRODUCT34,201639,2016,39,561.0,561.0,61.666667,12.464305,36.576923,61.666667
143,A00,PRODUCT34,201640,2016,40,17.0,17.0,56.800000,9.352368,36.576923,56.800000
144,A00,PRODUCT34,201641,2016,41,75.0,75.0,57.800000,3.233162,36.576923,57.800000
145,A00,PRODUCT34,201642,2016,42,10.0,10.0,58.533333,3.255612,36.576923,58.533333
146,A00,PRODUCT34,201643,2016,43,11.0,11.0,60.600000,13.250148,36.576923,60.600000
147,A00,PRODUCT34,201644,2016,44,15.0,15.0,65.333333,17.495968,36.576923,65.333333
148,A00,PRODUCT34,201645,2016,45,18.0,18.0,66.466667,21.010526,36.576923,66.466667
149,A00,PRODUCT34,201646,2016,46,14.0,14.0,59.733333,23.063482,36.576923,64.000000
150,A00,PRODUCT34,201647,2016,47,9.0,9.0,22.333333,23.943870,36.576923,25.769231
151,A00,PRODUCT34,201648,2016,48,17.0,17.0,21.200000,23.505508,36.576923,26.500000
152,A00,PRODUCT34,201649,2016,49,19.0,19.0,16.200000,20.805825,36.576923,22.090909
153,A00,PRODUCT34,201650,2016,50,35.0,35.0,15.533333,15.011753,36.576923,23.300000
154,A00,PRODUCT34,201651,2016,51,73.0,73.0,14.800000,3.965546,36.576923,24.666667
155,A00,PRODUCT34,201652,2016,52,22.0,22.0,13.800000,3.394604,36.576923,25.875000

In [316]:
def rolling_function(dataFrame, groupKey, rollingColumnName, window = 15,aggFunc = 0):
    groupDataSet = dataFrame.groupby(groupKey)
    groupDataSetList = list(groupDataSet.groups)
    rollingList = []
    for i in range(0, len(groupDataSetList)):
        rollingValue = groupDataSet.get_group(groupDataSetList[i])
        if (aggFunc == 0):
            rollingList += list(rollingValue[rollingColumnName].rolling(window = window, center = True, min_periods = 0).mean())
        else:
            rollingList += list(rollingValue[rollingColumnName].rolling(window = window, center = True, min_periods = 0).std(ddof = 1))
    return rollingList

In [318]:
list1 = rolling_function(dataFrame = mergedData, groupKey = ["REGIONID", "PRODUCT"], rollingColumnName = "NEW_QTY")

In [319]:
list1

[520.0,
 514.4444444444445,
 516.8,
 503.3636363636364,
 490.75,
 480.2307692307692,
 468.2142857142857,
 456.6666666666667,
 431.53333333333336,
 402.06666666666666,
 375.53333333333336,
 350.8,
 325.73333333333335,
 305.26666666666665,
 284.6666666666667,
 265.93333333333334,
 239.33333333333334,
 207.8,
 187.2,
 169.2,
 155.66666666666666,
 153.13333333333333,
 168.93333333333334,
 179.93333333333334,
 193.0,
 205.26666666666668,
 217.6,
 229.06666666666666,
 237.6,
 246.2,
 253.4,
 261.4,
 269.3333333333333,
 275.0,
 282.73333333333335,
 285.6666666666667,
 276.8666666666667,
 251.8,
 235.13333333333333,
 222.93333333333334,
 209.46666666666667,
 194.33333333333334,
 187.86666666666667,
 179.73333333333332,
 172.73333333333332,
 170.06666666666666,
 170.06666666666666,
 164.93333333333334,
 165.53333333333333,
 156.93333333333334,
 148.33333333333334,
 142.86666666666667,
 135.93333333333334,
 125.46666666666667,
 112.73333333333333,
 107.4,
 103.13333333333334,
 90.53333333333333,
 86.8,
 80.93333333333334,
 73.13333333333334,
 63.666666666666664,
 59.0,
 51.333333333333336,
 50.86666666666667,
 52.2,
 55.13333333333333,
 57.333333333333336,
 59.93333333333333,
 58.86666666666667,
 55.6,
 54.46666666666667,
 54.53333333333333,
 51.733333333333334,
 51.06666666666667,
 50.93333333333333,
 49.666666666666664,
 52.333333333333336,
 56.333333333333336,
 60.333333333333336,
 67.06666666666666,
 72.8,
 80.86666666666666,
 83.06666666666666,
 87.4,
 94.06666666666666,
 99.86666666666666,
 105.53333333333333,
 110.2,
 116.6,
 118.73333333333333,
 120.33333333333333,
 117.86666666666666,
 114.26666666666667,
 109.4,
 99.93333333333334,
 119.2,
 106.86666666666666,
 100.73333333333333,
 95.06666666666666,
 88.06666666666666,
 81.0,
 75.2,
 70.53333333333333,
 63.46666666666667,
 59.8,
 58.266666666666666,
 57.06666666666667,
 54.6,
 52.13333333333333,
 50.0,
 18.4,
 17.533333333333335,
 16.333333333333332,
 15.466666666666667,
 14.0,
 13.266666666666667,
 12.0,
 10.666666666666666,
 10.2,
 10.066666666666666,
 8.333333333333334,
 7.333333333333333,
 7.0,
 7.466666666666667,
 34.53333333333333,
 34.6,
 34.53333333333333,
 39.733333333333334,
 39.2,
 39.333333333333336,
 39.06666666666667,
 38.8,
 38.86666666666667,
 45.13333333333333,
 82.06666666666666,
 82.86666666666666,
 87.4,
 87.86666666666666,
 87.33333333333333,
 60.4,
 61.2,
 61.666666666666664,
 56.8,
 57.8,
 58.53333333333333,
 60.6,
 65.33333333333333,
 66.46666666666667,
 64.0,
 25.76923076923077,
 26.5,
 22.09090909090909,
 23.3,
 24.666666666666668,
 25.875,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.3333333333333333,
 0.5333333333333333,
 1.6,
 2.1333333333333333,
 2.8666666666666667,
 3.8,
 4.666666666666667,
 4.933333333333334,
 5.333333333333333,
 5.733333333333333,
 6.333333333333333,
 6.4,
 6.533333333333333,
 6.533333333333333,
 6.666666666666667,
 6.466666666666667,
 6.4,
 5.466666666666667,
 5.133333333333334,
 4.466666666666667,
 3.6,
 2.933333333333333,
 2.7333333333333334,
 2.4,
 2.1333333333333333,
 1.6666666666666667,
 1.6,
 1.4666666666666666,
 1.5333333333333334,
 1.6,
 1.6,
 1.9333333333333333,
 1.9333333333333333,
 2.0,
 2.2,
 2.4,
 2.466666666666667,
 2.6,
 2.7333333333333334,
 2.8,
 5.266666666666667,
 6.2,
 7.066666666666666,
 8.0,
 8.333333333333334,
 9.333333333333334,
 9.2,
 9.333333333333334,
 9.4,
 9.533333333333333,
 9.666666666666666,
 9.733333333333333,
 10.266666666666667,
 10.266666666666667,
 10.466666666666667,
 8.066666666666666,
 7.4,
 6.8,
 6.266666666666667,
 6.066666666666666,
 5.2,
 5.0,
 4.933333333333334,
 4.733333333333333,
 4.466666666666667,
 4.2,
 3.933333333333333,
 3.3333333333333335,
 3.2666666666666666,
 3.066666666666667,
 2.933333333333333,
 2.8,
 2.6666666666666665,
 2.4,
 2.1333333333333333,
 2.1333333333333333,
 2.066666666666667,
 2.0,
 2.2666666666666666,
 2.3333333333333335,
 2.3333333333333335,
 2.4,
 3.2,
 3.2666666666666666,
 3.2,
 4.8,
 9.0,
 13.0,
 15.0,
 18.133333333333333,
 20.666666666666668,
 24.666666666666668,
 28.0,
 30.0,
 32.0,
 33.86666666666667,
 35.53333333333333,
 36.666666666666664,
 37.46666666666667,
 38.4,
 37.733333333333334,
 70.93333333333334,
 91.13333333333334,
 151.53333333333333,
 215.93333333333334,
 259.4,
 286.46666666666664,
 326.46666666666664,
 490.8,
 529.8,
 575.6666666666666,
 629.1333333333333,
 664.4666666666667,
 704.0,
 738.0666666666667,
 766.8666666666667,
 753.4,
 751.3333333333334,
 713.2666666666667,
 662.7333333333333,
 632.1333333333333,
 616.6,
 583.0,
 428.73333333333335,
 398.2,
 359.8666666666667,
 313.26666666666665,
 285.3333333333333,
 255.13333333333333,
 234.2,
 212.8,
 195.46666666666667,
 182.6,
 169.73333333333332,
 163.0,
 154.26666666666668,
 140.46666666666667,
 131.86666666666667,
 127.92857142857143,
 125.46153846153847,
 124.0,
 123.45454545454545,
 121.6,
 117.88888888888889,
 106.0,
 11722.125,
 12091.555555555555,
 12471.9,
 12815.818181818182,
 13192.75,
 13517.846153846154,
 14158.142857142857,
 14681.4,
 15328.2,
 15913.933333333332,
 16449.866666666665,
 17021.866666666665,
 17591.6,
 18080.666666666668,
 18424.866666666665,
 19024.533333333333,
 19712.6,
 20236.333333333332,
 20870.8,
 21417.066666666666,
 22022.866666666665,
 22309.066666666666,
 22999.533333333333,
 23753.4,
 24763.466666666667,
 25951.4,
 27339.8,
 28811.0,
 30207.466666666667,
 31436.266666666666,
 32435.6,
 33575.46666666667,
 35378.6,
 36478.73333333333,
 37363.6,
 37984.333333333336,
 38554.73333333333,
 38673.46666666667,
 39047.333333333336,
 39483.6,
 39762.0,
 40046.2,
 39914.2,
 39859.4,
 40029.8,
 40533.333333333336,
 40908.333333333336,
 40773.666666666664,
 41125.6,
 41805.666666666664,
 42883.13333333333,
 43799.333333333336,
 44586.933333333334,
 44935.13333333333,
 45083.73333333333,
 45292.933333333334,
 45530.333333333336,
 45737.73333333333,
 46135.4,
 46317.13333333333,
 46044.46666666667,
 45409.46666666667,
 44757.13333333333,
 44474.4,
 43919.53333333333,
 42965.933333333334,
 42462.53333333333,
 42236.8,
 42743.26666666667,
 43468.46666666667,
 44007.73333333333,
 44464.86666666667,
 45378.0,
 46616.6,
 47421.066666666666,
 48436.333333333336,
 50325.933333333334,
 52205.066666666666,
 53492.46666666667,
 54752.8,
 56328.666666666664,
 57511.13333333333,
 58676.86666666667,
 59522.066666666666,
 59872.0,
 60597.73333333333,
 61291.8,
 61297.53333333333,
 60711.933333333334,
 60907.666666666664,
 61101.666666666664,
 60292.6,
 59120.53333333333,
 58458.333333333336,
 58299.0,
 58255.46666666667,
 58302.0,
 57841.86666666667,
 56883.0,
 55998.13333333333,
 54872.333333333336,
 53716.8,
 52804.53333333333,
 51591.933333333334,
 49716.8,
 47730.066666666666,
 46428.86666666667,
 45472.333333333336,
 44115.86666666667,
 43327.666666666664,
 41496.066666666666,
 40446.4,
 38957.4,
 37486.53333333333,
 36409.0,
 35442.8,
 34103.333333333336,
 33007.0,
 32181.933333333334,
 31488.933333333334,
 31146.666666666668,
 30291.333333333332,
 30140.466666666667,
 29971.8,
 28821.733333333334,
 28238.733333333334,
 26879.333333333332,
 26425.066666666666,
 26157.466666666667,
 25488.8,
 24578.533333333333,
 24070.133333333335,
 23711.733333333334,
 23058.466666666667,
 22913.866666666665,
 22518.066666666666,
 22515.133333333335,
 21273.133333333335,
 20501.733333333334,
 19649.2,
 19312.333333333332,
 19162.0,
 18782.4,
 18655.0,
 18638.4,
 19136.0,
 19726.266666666666,
 20383.533333333333,
 21507.2,
 21580.5,
 21618.69230769231,
 21555.083333333332,
 22209.363636363636,
 22606.1,
 23413.777777777777,
 23917.0,
 11801.125,
 11494.888888888889,
 11159.5,
 10839.09090909091,
 10577.75,
 10325.23076923077,
 10030.5,
 9829.533333333333,
 9314.533333333333,
 9150.266666666666,
 8122.733333333334,
 7868.266666666666,
 7569.0,
 7299.0,
 7140.533333333334,
 6917.4,
 6840.6,
 6756.666666666667,
 6775.533333333334,
 6745.133333333333,
 6704.466666666666,
 6739.8,
 6663.266666666666,
 6780.533333333334,
 6811.8,
 7019.6,
 7064.866666666667,
 7421.6,
 7457.666666666667,
 7473.0,
 7661.666666666667,
 7602.466666666666,
 7628.266666666666,
 7540.533333333334,
 7435.8,
 7408.133333333333,
 7331.466666666666,
 7503.133333333333,
 7471.0,
 7693.266666666666,
 8278.8,
 8728.733333333334,
 8770.666666666666,
 9207.133333333333,
 9660.8,
 9728.2,
 9742.133333333333,
 9673.933333333332,
 9790.266666666666,
 10129.2,
 10151.8,
 10190.066666666668,
 10081.0,
 10089.8,
 9785.8,
 8958.066666666668,
 8430.0,
 8002.0,
 7418.6,
 6775.6,
 6358.533333333334,
 6165.333333333333,
 6045.666666666667,
 5740.4,
 5351.066666666667,
 5196.133333333333,
 5114.866666666667,
 4976.733333333334,
 4779.466666666666,
 4726.6,
 4894.2,
 4996.6,
 5107.0,
 5284.0,
 5338.933333333333,
 5381.0,
 5417.533333333334,
 5435.066666666667,
 5500.133333333333,
 5488.133333333333,
 5553.466666666666,
 5588.4,
 5547.066666666667,
 5509.266666666666,
 5482.933333333333,
 5256.933333333333,
 5139.866666666667,
 5073.533333333334,
 4928.0,
 4956.333333333333,
 5042.0,
 5265.333333333333,
 6066.333333333333,
 6594.8,
 6953.266666666666,
 7395.866666666667,
 7698.733333333334,
 7888.466666666666,
 7992.6,
 8139.6,
 8311.133333333333,
 8322.0,
 8304.066666666668,
 8300.266666666666,
 8196.666666666666,
 7999.666666666667,
 7664.733333333334,
 6750.6,
 6060.2,
 5566.133333333333,
 4960.466666666666,
 4446.133333333333,
 4136.2,
 3887.4666666666667,
 3547.8,
 3191.133333333333,
 2998.133333333333,
 2749.3333333333335,
 2536.133333333333,
 2359.4666666666667,
 2262.8,
 2173.866666666667,
 2095.2,
 2060.8,
 1988.0666666666666,
 1918.4,
 1886.4,
 1830.4666666666667,
 1773.0,
 1716.1333333333334,
 1687.4666666666667,
 1602.4666666666667,
 1533.4666666666667,
 1455.9333333333334,
 1386.2,
 1297.6,
 1208.0666666666666,
 1122.6,
 1034.8666666666666,
 963.8,
 875.6666666666666,
 790.6666666666666,
 736.0666666666667,
 717.4,
 702.2,
 638.6666666666666,
 596.4666666666667,
 552.6,
 548.0,
 544.7857142857143,
 542.3846153846154,
 544.8333333333334,
 543.9090909090909,
 550.0,
 550.1111111111111,
 562.375,
 140047.25,
 140917.22222222222,
 141398.8,
 140593.0,
 139758.5,
 138700.15384615384,
 136925.85714285713,
 134768.8,
 132196.66666666666,
 131992.93333333332,
 131772.33333333334,
 130137.4,
 126572.26666666666,
 126110.8,
 124167.6,
 120915.8,
 119825.73333333334,
 118130.0,
 117711.13333333333,
 119376.0,
 118988.26666666666,
 119519.73333333334,
 119598.46666666666,
 121051.46666666666,
 121812.13333333333,
 123195.4,
 124924.13333333333,
 128274.53333333334,
 130726.2,
 129768.86666666667,
 130473.73333333334,
 129212.66666666667,
 129170.93333333333,
 128935.66666666667,
 126052.06666666667,
 125454.93333333333,
 125168.6,
 127301.6,
 127869.06666666667,
 140210.46666666667,
 219834.06666666668,
 240798.86666666667,
 244388.33333333334,
 256487.53333333333,
 269446.2,
 271546.3333333333,
 272297.3333333333,
 271968.86666666664,
 272931.4666666667,
 277479.3333333333,
 279349.3333333333,
 281278.6,
 282547.0,
 283249.26666666666,
 273282.86666666664,
 194245.13333333333,
 173995.93333333332,
 168785.8,
 155539.06666666668,
 143571.26666666666,
 142543.53333333333,
 142762.73333333334,
 144077.6,
 143511.33333333334,
 139867.8,
 139443.26666666666,
 139226.93333333332,
 137128.8,
 136979.93333333332,
 135354.2,
 134667.73333333334,
 136854.4,
 137007.8,
 138174.26666666666,
 138507.53333333333,
 138535.46666666667,
 139028.86666666667,
 140071.4,
 142713.73333333334,
 144294.2,
 149434.0,
 152892.33333333334,
 153397.0,
 152757.13333333333,
 153481.33333333334,
 152981.86666666667,
 149782.46666666667,
 148552.06666666668,
 147119.26666666666,
 148521.53333333333,
 151422.2,
 167673.86666666667,
 251022.8,
 284450.0,
 294117.26666666666,
 303868.26666666666,
 319025.73333333334,
 321021.13333333336,
 321500.73333333334,
 322376.3333333333,
 326998.8,
 333309.13333333336,
 336515.0,
 338370.4,
 336701.6,
 334695.4,
 318977.8,
 235682.86666666667,
 199887.46666666667,
 189301.4,
 175472.33333333334,
 156853.13333333333,
 155194.86666666667,
 155534.4,
 156187.53333333333,
 153249.06666666668,
 148562.33333333334,
 150812.6,
 154386.26666666666,
 156518.46666666667,
 157681.33333333334,
 158661.86666666667,
 161700.13333333333,
 165403.8,
 169091.6,
 170047.33333333334,
 171762.26666666666,
 174542.46666666667,
 179402.13333333333,
 182001.93333333332,
 183924.0,
 188527.26666666666,
 190284.66666666666,
 187143.4,
 187989.73333333334,
 188324.93333333332,
 189476.4,
 187503.53333333333,
 184675.46666666667,
 182487.86666666667,
 183541.66666666666,
 185090.53333333333,
 202581.4,
 299116.86666666664,
 333133.4666666667,
 339578.5333333333,
 345597.93333333335,
 356881.73333333334,
 359573.4666666667,
 372780.28571428574,
 387869.53846153844,
 405645.75,
 427350.2727272727,
 455493.9,
 488516.44444444444,
 527208.75,
 8411.375,
 8476.777777777777,
 8557.7,
 8600.363636363636,
 8552.583333333334,
 8551.461538461539,
 8498.214285714286,
 8420.266666666666,
 8333.4,
 8387.533333333333,
 8331.4,
 8391.666666666666,
 8582.0,
 8966.8,
 9606.466666666667,
 9599.933333333332,
 9801.333333333334,
 10061.933333333332,
 10562.866666666667,
 12001.733333333334,
 12907.266666666666,
 12929.133333333333,
 13036.866666666667,
 13138.333333333334,
 13428.133333333333,
 13746.4,
 14057.266666666666,
 14655.866666666667,
 15284.933333333332,
 14579.266666666666,
 14474.666666666666,
 14312.4,
 14132.466666666667,
 13642.533333333333,
 12320.866666666667,
 11422.6,
 11412.866666666667,
 12047.2,
 12933.8,
 13628.4,
 15554.866666666667,
 16519.2,
 16031.866666666667,
 15129.666666666666,
 15367.6,
 15835.933333333332,
 16027.2,
 16020.266666666666,
 16297.133333333333,
 16475.333333333332,
 16684.733333333334,
 17317.6,
 17288.533333333333,
 16574.666666666668,
 15788.066666666668,
 13756.4,
 12802.466666666667,
 12938.666666666666,
 12941.6,
 12910.533333333333,
 12649.266666666666,
 12630.4,
 12827.466666666667,
 12893.066666666668,
 13096.333333333334,
 13880.666666666666,
 14674.0,
 14720.4,
 14820.0,
 15162.466666666667,
 15995.733333333334,
 17388.533333333333,
 18596.6,
 19622.0,
 19946.866666666665,
 20173.733333333334,
 20246.333333333332,
 20274.4,
 20258.133333333335,
 20350.666666666668,
 20427.0,
 20466.666666666668,
 20702.266666666666,
 20877.866666666665,
 20709.933333333334,
 20216.066666666666,
 18969.266666666666,
 17782.333333333332,
 16682.666666666668,
 17050.666666666668,
 18175.8,
 19463.133333333335,
 22255.8,
 24141.266666666666,
 24314.4,
 23940.8,
 23146.2,
 22955.0,
 22669.8,
 22752.533333333333,
 22810.133333333335,
 22875.266666666666,
 23252.133333333335,
 24062.266666666666,
 23812.133333333335,
 22594.4,
 21324.933333333334,
 18501.933333333334,
 16641.666666666668,
 16286.2,
 16106.0,
 16017.866666666667,
 15794.133333333333,
 15863.333333333334,
 15659.4,
 15413.666666666666,
 15439.933333333332,
 15843.8,
 16446.6,
 16530.666666666668,
 16638.2,
 17569.6,
 18927.866666666665,
 20466.933333333334,
 21960.666666666668,
 22684.266666666666,
 23453.066666666666,
 24410.6,
 25145.533333333333,
 25817.8,
 26842.666666666668,
 28454.666666666668,
 29866.4,
 29981.6,
 30057.8,
 30180.866666666665,
 29355.733333333334,
 28213.8,
 26670.066666666666,
 24986.4,
 24428.2,
 23753.933333333334,
 23165.4,
 24808.533333333333,
 26287.4,
 26319.0,
 25373.533333333333,
 24108.8,
 23881.066666666666,
 24090.14285714286,
 24579.923076923078,
 25367.916666666668,
 26168.727272727272,
 27346.3,
 29128.0,
 30410.0,
 4396.125,
 4332.555555555556,
 4268.7,
 4263.636363636364,
 4387.166666666667,
 4400.923076923077,
 4400.071428571428,
 4448.666666666667,
 4386.933333333333,
 4359.933333333333,
 4370.066666666667,
 4428.8,
 4457.933333333333,
 4558.8,
 4476.4,
 4515.533333333334,
 4598.666666666667,
 4592.0,
 4566.266666666666,
 4548.066666666667,
 4539.133333333333,
 4628.866666666667,
 4639.933333333333,
 4614.8,
 4736.0,
 4817.2,
 4896.266666666666,
 4987.066666666667,
 4958.866666666667,
 4862.533333333334,
 4927.4,
 4834.6,
 4888.2,
 4878.0,
 4807.2,
 4750.066666666667,
 4644.6,
 4661.466666666666,
 4703.6,
 4687.0,
 4927.2,
 5122.6,
 5234.333333333333,
 5643.466666666666,
 6156.466666666666,
 6306.6,
 6367.133333333333,
 6428.2,
 6464.666666666667,
 6664.733333333334,
 6789.066666666667,
 6922.0,
 6879.0,
 6927.8,
 6944.133333333333,
 6606.066666666667,
 6241.4,
 6070.0,
 5613.6,
 5115.066666666667,
 4925.933333333333,
 4895.2,
 4850.066666666667,
 4850.333333333333,
 ...]

In [353]:
def groupRolling(oneGroup):
    indexGroupData = oneGroup.reset_index(drop = True)
    indexGroupData["MA"] = indexGroupData["QTY"].rolling(window = 15, center = True, min_periods = 0).mean()
    return indexGroupData
finalResult = mergedData.groupby(groupKey).apply(groupRolling).reset_index(drop = True)

In [354]:
finalResult

,REGIONID,PRODUCT,YEARWEEK,YEAR,WEEK,QTY,NEW_QTY,MA,MSTD,GROUP,MA3
0,A00,PRODUCT34,201401,2014,1,661.0,661.0,520.000000,12.002994,275.961538,520.000000
1,A00,PRODUCT34,201402,2014,2,679.0,679.0,514.444444,15.933923,275.961538,514.444444
2,A00,PRODUCT34,201403,2014,3,578.0,578.0,516.800000,19.930825,275.961538,516.800000
3,A00,PRODUCT34,201404,2014,4,532.0,532.0,503.363636,23.784855,275.961538,503.363636
4,A00,PRODUCT34,201405,2014,5,516.0,516.0,490.750000,30.428905,275.961538,490.750000
5,A00,PRODUCT34,201406,2014,6,423.0,423.0,480.230769,38.666084,275.961538,480.230769
6,A00,PRODUCT34,201407,2014,7,407.0,407.0,468.214286,47.192218,275.961538,468.214286
7,A00,PRODUCT34,201408,2014,8,364.0,364.0,456.666667,53.509329,275.961538,456.666667
8,A00,PRODUCT34,201409,2014,9,470.0,470.0,431.533333,59.591171,275.961538,431.533333
9,A00,PRODUCT34,201410,2014,10,538.0,538.0,402.066667,64.038426,275.961538,402.066667
10,A00,PRODUCT34,201411,2014,11,369.0,369.0,375.533333,66.380349,275.961538,375.533333
11,A00,PRODUCT34,201412,2014,12,352.0,352.0,350.800000,66.197096,275.961538,350.800000
12,A00,PRODUCT34,201413,2014,13,354.0,354.0,325.733333,64.231478,275.961538,325.733333
13,A00,PRODUCT34,201414,2014,14,312.0,312.0,305.266667,63.843278,275.961538,305.266667
14,A00,PRODUCT34,201415,2014,15,295.0,295.0,284.666667,63.749723,275.961538,284.666667
15,A00,PRODUCT34,201416,2014,16,284.0,284.0,265.933333,63.198917,275.961538,265.933333
16,A00,PRODUCT34,201417,2014,17,237.0,237.0,239.333333,61.427301,275.961538,239.333333
17,A00,PRODUCT34,201418,2014,18,180.0,180.0,207.800000,57.375527,275.961538,207.800000
18,A00,PRODUCT34,201419,2014,19,161.0,161.0,187.200000,49.053944,275.961538,187.200000
19,A00,PRODUCT34,201420,2014,20,140.0,140.0,169.200000,38.741811,275.961538,169.200000
20,A00,PRODUCT34,201421,2014,21,116.0,116.0,155.666667,27.242451,275.961538,155.666667
21,A00,PRODUCT34,201422,2014,22,98.0,98.0,153.133333,19.953467,275.961538,153.133333
22,A00,PRODUCT34,201423,2014,23,83.0,83.0,168.933333,21.837712,275.961538,168.933333
23,A00,PRODUCT34,201424,2014,24,71.0,71.0,179.933333,27.119202,275.961538,179.933333
24,A00,PRODUCT34,201425,2014,25,65.0,65.0,193.000000,31.179979,275.961538,193.000000
25,A00,PRODUCT34,201426,2014,26,60.0,60.0,205.266667,32.091497,275.961538,205.266667
26,A00,PRODUCT34,201427,2014,27,82.0,82.0,217.600000,29.774486,275.961538,217.600000
27,A00,PRODUCT34,201428,2014,28,151.0,151.0,229.066667,27.962398,275.961538,229.066667
28,A00,PRODUCT34,201429,2014,29,274.0,274.0,237.600000,25.816728,275.961538,237.600000
29,A00,PRODUCT34,201430,2014,30,532.0,532.0,246.200000,23.610884,275.961538,246.200000
...,...,...,...,...,...,...,...,...,...,...,...
123834,A77,PRODUCT12,201623,2016,23,5348.0,5348.0,4159.933333,190.905116,4837.153846,4159.933333
123835,A77,PRODUCT12,201624,2016,24,3275.0,3275.0,4272.333333,207.589152,4837.153846,4272.333333
123836,A77,PRODUCT12,201625,2016,25,4158.0,4158.0,4435.133333,216.801024,4837.153846,4435.133333
123837,A77,PRODUCT12,201626,2016,26,4815.0,4815.0,4530.533333,208.190473,4837.153846,4530.533333
123838,A77,PRODUCT12,201627,2016,27,3002.0,3002.0,4518.466667,129.945597,4837.153846,4518.466667
123839,A77,PRODUCT12,201628,2016,28,3319.0,3319.0,4527.000000,257.294323,4837.153846,4527.000000
123840,A77,PRODUCT12,201629,2016,29,4200.0,4200.0,4528.533333,305.860200,4837.153846,4528.533333
123841,A77,PRODUCT12,201630,2016,30,7120.0,7120.0,4402.866667,330.341675,4837.153846,4402.866667
123842,A77,PRODUCT12,201631,2016,31,6345.0,6345.0,4418.533333,356.976864,4837.153846,4418.533333
123843,A77,PRODUCT12,201632,2016,32,5863.0,5863.0,5182.466667,386.509085,4837.153846,5182.466667
123844,A77,PRODUCT12,201633,2016,33,4211.0,4211.0,5145.466667,391.062864,4837.153846,5145.466667
123845,A77,PRODUCT12,201634,2016,34,4019.0,4019.0,5091.800000,359.771696,4837.153846,5091.800000
123846,A77,PRODUCT12,201635,2016,35,3624.0,3624.0,5177.800000,274.320890,4837.153846,5177.800000
123847,A77,PRODUCT12,201636,2016,36,3742.0,3742.0,5340.533333,146.471329,4837.153846,5340.533333
123848,A77,PRODUCT12,201637,2016,37,3002.0,3002.0,5334.466667,172.824989,4837.153846,5334.466667
123849,A77,PRODUCT12,201638,2016,38,5583.0,5583.0,5160.200000,181.622102,4837.153846,5160.200000
123850,A77,PRODUCT12,201639,2016,39,14734.0,14734.0,5020.866667,181.622311,4837.153846,5020.866667
123851,A77,PRODUCT12,201640,2016,40,3603.0,3603.0,4868.266667,180.765271,4837.153846,4868.266667
123852,A77,PRODUCT12,201641,2016,41,4010.0,4010.0,4864.333333,206.021515,4837.153846,4864.333333
123853,A77,PRODUCT12,201642,2016,42,4292.0,4292.0,4935.466667,226.688236,4837.153846,4935.466667
123854,A77,PRODUCT12,201643,2016,43,5760.0,5760.0,5083.600000,256.371104,4837.153846,5083.600000
123855,A77,PRODUCT12,201644,2016,44,4109.0,4109.0,5163.000000,267.354423,4837.153846,5163.000000
123856,A77,PRODUCT12,201645,2016,45,4506.0,4506.0,5466.266667,263.886909,4837.153846,5466.266667
123857,A77,PRODUCT12,201646,2016,46,4255.0,4255.0,5457.928571,256.421626,4837.153846,5457.928571
123858,A77,PRODUCT12,201647,2016,47,3574.0,3574.0,4744.384615,259.694470,4837.153846,4744.384615
123859,A77,PRODUCT12,201648,2016,48,4152.0,4152.0,4839.500000,260.550638,4837.153846,4839.500000
123860,A77,PRODUCT12,201649,2016,49,5086.0,5086.0,4914.909091,274.767625,4837.153846,4914.909091
123861,A77,PRODUCT12,201650,2016,50,5846.0,5846.0,4977.200000,229.386294,4837.153846,4977.200000
123862,A77,PRODUCT12,201651,2016,51,4933.0,4933.0,4890.222222,91.131622,4837.153846,4890.222222
123863,A77,PRODUCT12,201652,2016,52,7551.0,7551.0,4987.875000,61.751302,4837.153846,4987.875000

In [367]:
# 마지막 4주차 평균
def rolling_function(dataFrame, groupKey, rollingColumnName):
    groupDataSet = dataFrame.groupby(groupKey)
    groupDataSetList = list(groupDataSet.groups)
    rollingList = []
    for i in range(0, len(groupDataSetList)):
        rollingValue = groupDataSet.get_group(groupDataSetList[i])
        rollingList += [sum(rollingValue[rollingColumnName][-4:]) / 4]
    return rollingList

In [369]:
print(rolling_function(dataFrame = mergedData, groupKey = ["REGIONID", "PRODUCT"], rollingColumnName = "NEW_QTY"))

[37.25, 76.25, 28398.75, 390.75, 302132.0, 27785.0, 3182.75, 2450.5, 4524.5, 55872.75, 74.5, 20023.25, 363767.0, 50745.0, 11269.75, 8492.5, 5279.5, 98784.0, 881358.25, 12933.0, 1.5, 18398.5, 74610.0, 4386.75, 29512.5, 136.25, 56.5, 22953.5, 3419.0, 228.0, 11916.5, 3150.25, 54531.25, 8448.75, 2359.5, 581.0, 125.25, 7300.5, 69648.25, 1.0, 0.5, 1207.0, 7962.5, 42.5, 30617.0, 257.25, 47.5, 1417.0, 11135.25, 1654.75, 23691.5, 1734.0, 1154.25, 437.0, 2560.75, 3797.5, 243290.25, 1.25, 2761.5, 3748.5, 1.0, 9980.5, 50.25, 208.75, 8.75, 62.25, 796.5, 7276.5, 915.25, 955.25, 1.5, 188.75, 802.75, 4576.75, 99724.5, 2.25, 469.5, 112.25, 10.75, 3913.0, 1.5, 533.75, 177.25, 4.0, 494.0, 231.5, 8690.5, 1699.0, 8.75, 33.75, 253.5, 91.25, 1084.75, 112955.0, 285.75, 1003.0, 460.0, 1667.75, 97.0, 3085.75, 10.75, 155.25, 1364.25, 19565.25, 115.25, 163.25, 7.5, 5286.5, 355.75, 49.5, 906.75, 3762.75, 0.0, 372.75, 6.0, 52.75, 104.5, 188.75, 25252.5, 491.5, 0.0, 60.75, 111.0, 16117.5, 209.0, 0.25, 93.5, 1890.5, 17488.25, 0.0, 3022.75, 5.25, 28.25, 141.25, 25.75, 2250.25, 69817.25, 714.5, 0.0, 2126.5, 15.0, 19896.5, 85.75, 1032.25, 944.5, 29059.0, 1857.5, 57654.0, 3393.0, 81.0, 93.75, 547.5, 283.0, 9862.75, 197479.75, 1229.25, 0.0, 3305.25, 1015.5, 52481.75, 122.0, 0.0, 757.0, 13803.5, 2415.75, 68167.75, 7664.75, 0.0, 17.5, 430.25, 13738.5, 215620.75, 836.75, 0.25, 16167.75, 173.5, 6080.0, 525.25, 91.75, 149.25, 2432.5, 311.75, 4.75, 22.75, 0.0, 278.0, 35793.0, 485.5, 104.5, 108.75, 39349.0, 576.5, 529.0, 101.0, 2236.0, 35884.5, 1354.0, 26.75, 18.5, 222.25, 817.75, 4126.25, 217550.75, 1646.25, 481.5, 163.25, 15716.75, 341.5, 0.0, 31.5, 1397.5, 10327.5, 2168.25, 2966.5, 408.5, 693.75, 0.5, 55.0, 2.5, 128.5, 11.0, 176.75, 1058.25, 66487.25, 716.25, 2904.75, 87.5, 5.0, 28.75, 27709.25, 13.5, 60.5, 209.0, 168.5, 2454.0, 13718.0, 0.0, 2913.5, 19.25, 2049.25, 519.75, 40.0, 161.25, 54.5, 139.25, 101.5, 557.0, 1467.0, 94818.5, 3634.0, 788.25, 509.5, 88.0, 131.0, 18179.75, 15.5, 473.5, 291.75, 17915.25, 1187.0, 23430.5, 0.0, 1393.25, 24.75, 5.0, 133.0, 84.0, 3250.75, 91782.25, 42.25, 812.75, 1056.0, 26.5, 43752.25, 148.25, 44.25, 752.25, 82.0, 6399.0, 62852.5, 5186.75, 12382.5, 85.5, 0.0, 134.25, 17.5, 7.75, 0.5, 1810.25, 4690.25, 142394.25, 1921.0, 12498.0, 162.0, 0.0, 11.5, 3.0, 14800.75, 112.0, 173.75, 2362.5, 424.25, 3718.25, 851.5, 106.0, 141.75, 1146.0, 471.25, 97632.0, 0.25, 2292.25, 890.5, 0.25, 55567.5, 2.0, 0.25, 4844.75, 2862.75, 24630.5, 1.75, 1177.25, 3.25, 39.75, 53.25, 599.0, 3985.0, 529457.25, 16.0, 515.5, 819.25, 70202.25, 5394.25, 269.5, 177340.5, 2.5, 1714.25, 10.25, 15.25, 30.75, 356.25, 1576.0, 301.75, 0.0, 125.5, 545.25, 997.0, 18027.25, 63.75, 574.75, 155.75, 30130.0, 1263.75, 7274.25, 234.25, 6117.25, 378.0, 93272.25, 4427.5, 70.0, 12127.25, 8.0, 149.5, 0.0, 1051.5, 19274.0, 0.0, 3657.25, 1492.5, 305.0, 2091.5, 3745.5, 47150.25, 1193.5, 1562.75, 3233.75, 12360.25, 1.25, 605.5, 91.75, 0.25, 832.25, 8343.25, 583.5, 0.0, 0.75, 237.5, 2474.5, 370.25, 242747.5, 2733.25, 62.75, 1.75, 12331.75, 0.0, 0.0, 269.0, 235.75, 4175.75, 121.25, 21.75, 268.75, 4293.5, 147.25, 65595.25, 405.5, 1997.0, 0.0, 15910.5, 18.5, 139.5, 36.5, 4528.25, 518.0, 6868.0, 949.0, 226.5, 0.0, 51.25, 5115.5, 700.5, 164161.25, 8.0, 0.0, 4647.75, 380.0, 16105.5, 31.75, 0.25, 3216.5, 1497.25, 13826.25, 50.75, 9138.0, 8.5, 259.0, 6144.75, 1401.5, 510084.0, 0.0, 6223.0, 2.0, 0.75, 4186.5, 291.75, 0.25, 163.75, 4243.5, 646.0, 0.5, 0.0, 151.25, 1705.0, 889.25, 98642.5, 5.25, 1707.5, 335.75, 877.75, 104.25, 72411.75, 649.75, 18.75, 30651.25, 11.0, 11039.25, 0.0, 566.75, 239.5, 280.0, 15207.0, 527.5, 19.0, 329.0, 936.0, 937.0, 139018.5, 453.0, 1743.25, 232.25, 4665.25, 176.0, 162806.75, 4032.25, 7473.0, 966.75, 83447.75, 450.5, 243.5, 12349.5, 114.25, 951.0, 17.25, 15212.25, 0.0, 62.25, 590.0, 24.25, 191.5, 17.75, 52021.75, 90.0, 20.0, 0.75, 5761.5, 12.25, 54.5, 117.5, 13.75, 0.0, 8.25, 88.75, 39.25, 229.5, 4559.75, 0.0, 433.5, 0.5, 1.75, 0.0, 36.25, 1419.0, 35823.25, 103.0, 0.0, 918.0, 0.0, 0.0, 258.5, 0.0, 1445.25, 5.0, 0.75, 428.5, 55101.75, 561.5, 596.75, 5051.75, 20219.5, 1494.25, 2.75, 6.25, 142.0, 61.75, 3728.75, 230466.5, 1850.25, 132.75, 43978.25, 6109.0, 1629.5, 228512.25, 523.0, 3.0, 19018.75, 25.0, 4139.5, 9.5, 18.75, 63.5, 230.5, 1769.75, 360.75, 2.0, 17.75, 0.25, 222.75, 16576.25, 212.0, 23.25, 9.0, 4752.75, 2369.75, 2147.75, 1.0, 21.75, 138.75, 75.5, 46018.0, 653.25, 23.5, 9170.75, 1812.0, 4360.0, 0.25, 0.75, 105.0, 63.25, 599.75, 45095.5, 1430.5, 549.5, 607.0, 20636.0, 12749.0, 18376.25, 15110.75, 178219.5, 6490.0, 10832.0, 35.0, 7098.0, 79.0, 2103.75, 2421.5, 416.25, 2643.75, 1301.5, 1911.25, 310.25, 0.0, 4638.0, 2.75, 5750.75, 2.75, 5526.25, 69.5, 1791.25, 3227.5, 33.0, 1.75, 26.75, 1778.75, 173.5, 62403.25, 120.0, 28.5, 11379.25, 40.5, 462.5, 588.75, 394.25, 5731.5, 551.25, 27.5, 9.75, 146.25, 1311.25, 55151.25, 848.25, 466.5, 54.0, 9640.75, 25.0, 0.0, 2487.25, 10641.5, 0.75, 611.75, 67.5, 78.75, 2100.0, 3343.5, 106832.75, 531.5, 161.75, 0.5, 1.25, 13484.75, 114.0, 3.25, 12702.5, 476.0, 6.5, 20089.0, 0.0, 13119.5, 0.0, 42.25, 2305.75, 183.75, 118.75, 7876.5, 1714.5, 0.0, 24.0, 161.25, 4630.25, 211.5, 63977.75, 0.0, 2993.5, 2269.25, 4.0, 6186.0, 23.75, 26.25, 51.25, 1522.5, 45.0, 9.0, 2.5, 147.75, 39953.25, 19.75, 11.0, 199.0, 20771.0, 619.25, 3701.0, 0.0, 48.75, 61.0, 928.5, 78339.5, 848.25, 1.75, 2524.25, 25.0, 72.75, 286.75, 1927.25, 0.0, 86.0, 2.0, 6.5, 13.25, 126.0, 15412.75, 74.5, 127.75, 0.75, 1533.75, 58.0, 5995.0, 12.25, 1.75, 11.5, 176.75, 539.0, 39414.5, 311.75, 5.75, 299.25, 57.75, 18880.0, 479.75, 6.0, 428.25, 3630.25, 1.5, 2.0, 14.0, 297.25, 436.25, 136735.0, 46.5, 846.25, 16.5, 11296.0, 77.0, 6565.25, 70.25, 57.5, 5.0, 149.25, 6410.0, 1457.25, 0.0, 47.25, 1478.5, 22010.0, 24.75, 0.0, 1362.5, 10.0, 2713.25, 21.0, 194.0, 4967.75, 21.25, 94.0, 108.0, 177.0, 810.75, 23542.5, 120.75, 229.0, 174.75, 1.25, 3189.5, 931.25, 76.75, 18390.5, 43.5, 0.25, 2412.25, 271.75, 1.75, 13593.5, 2046.75, 52.0, 91848.0, 3768.5, 5854.0]